### ISSUE TITLE
No Readme

### ISSUE THREAD

**Issue by nickrod518** [xXTheAwesomerXx/CMUtils#1]
Hi, I was wondering if you were willing to provide instructions for compiling/running your project. I'm very interested in finding tools to make CM a little easier to deal with, and would be willing to write up instructions myself if I knew what was necessary. It doesn't look like this is an active project anymore, but I would appreciate any assistance you're willing to give.

**Comment by BORN4BAD** [comment]
This project isn't being development anymore. The code however still does
work. I've also been working on a C++ project which doesn't require Java to
be ran, which is precisely the downside to this project. Simply import the
project to Eclipse or another IDE, link the necessary Java JDK and JRE, and
run the program. It asks for the CM hostname/ip address, and it's
credentials.

**Comment by nickrod518** [comment]
Thanks! I was able to run the project, however it fails to connect to the server. I am able to ping the server and going to https://<cucmserver>/axl/ reports the service is running and accepting requests. I also verified my account is a member of the Standard AXL API Access group. Following steps here: http://www.cisco.com/en/US/products/sw/voicesw/ps556/prod_troubleshooting_guide_chapter09186a00801f096f.html it appears the  /CCMAPI/AXL/V1/SOAPISAPI.dll  resource is not available. Bummer :(

**Comment by BORN4BAD** [comment]
If I'm not mistaken only support for version 8.5 of CUCM is implemented in this project. Sorry for the inconvenience. When I get permission to release the C++ version I will shoot you an email.
